# [Usage]
#
# $ gem install gem_comet
# $ gem_comet release {version number, like as "1.2.3"}

version: 1.1

release:
  base_branch: master
  release_branch: production
  version_file_path: lib/rubocop_challenger/version.rb
  changelog_file_path: CHANGELOG.md # optional
