require: rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# For integration testing
RSpec/MultipleExpectations:
  Exclude:
    - 'spec/rubocop_challenger/cli_spec.rb'
