# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1

references:
  - &ruby_version
    ruby_version:
      type: enum
      enum: ['2.4', '2.5', '2.6', 'latest']
      default: '2.4'

executors:
  default:
    parameters:
      <<: *ruby_version
    docker:
       - image: circleci/ruby:<< parameters.ruby_version >>-node-browsers
    working_directory: ~/repo

commands:
  download_cc_test_reporter:
    steps:
      - run:
          name: Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
  restore_bundle_install_cache:
    steps:
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-
  bundle_install:
    steps:
      - run:
          name: Bundle Install
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
  save_bundle_install_cache:
    steps:
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
  run_rspec:
    description: 'Run RSpec'
    steps:
      - run:
          name: 'Execute RSpec'
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            ./tmp/cc-test-reporter before-build
            bundle exec rspec --format documentation \
                              --color \
                              --format RspecJunitFormatter \
                              --out /tmp/test-results/rspec.xml \
                              $TEST_FILES
            ./tmp/cc-test-reporter after-build --coverage-input-type simplecov --exit-code $?
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
  rubocop:
    steps:
      - run: bundle exec rubocop
  yardoc:
    steps:
      - run:  bundle exec yardoc -o ./yardoc
      - store_artifacts:
          path: ./yardoc
          destination: yardoc
  rake_build:
    steps:
      - run:
          name: Rake Build
          command: bundle exec rake build
  rubocop_challenge:
    steps:
      - run:
          name: Rubocop Challenge
          command: |
            bundle install
            bundle exec rubocop_challenger go \
              --email=ryz310@gmail.com \
              --name=ryz310 \
              --template=./lib/templates/checklist.md.erb \
              --no-auto-gen-timestamp \
              --exclude-limit=30
  release:
    description: Release to RubyGems.org
    steps:
      - run:
          name: Create Rubygems Credentials
          command: |
            mkdir ~/.gem
            echo -e "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}" > ~/.gem/credentials
            chmod 0600 ~/.gem/credentials
      - run:
          name: Release Gem
          command: |
            git push --set-upstream origin ${CIRCLE_BRANCH}
            bundle exec rake release --trace
  setup:
    description: Setup for Job Working
    steps:
      - checkout
      - restore_bundle_install_cache
      - bundle_install
      - save_bundle_install_cache
  test_and_build:
    description: Build the RubyGem
    steps:
      - download_cc_test_reporter
      - run_rspec
      - rake_build

jobs:
  build:
    parameters:
      <<: *ruby_version
    executor:
      name: default
      ruby_version: << parameters.ruby_version >>
    steps:
      - setup
      - test_and_build
  rubocop:
    executor: default
    steps:
      - setup
      - rubocop
  yardoc:
    executor: default
    steps:
      - setup
      - yardoc
  verify_rubocop_challenge:
    executor: default
    steps:
      - setup
      - run: bundle exec rake install
      - run:
          name: Jailbreak
          command: |
            git config --global user.email "testing@example.com"
            git config --global user.name "Testing"
            bundle exec bin/jailbreak
            git commit -am "jailbreak"
      - run:
          name: Verify Rubocop Challenge
          command: |
            bundle exec exe/rubocop_challenger go \
              --email=ryz310@gmail.com \
              --name=ryz310 \
              --mode=random \
              --no-create-pr
  rubocop_challenge:
    executor: default
    steps:
      - checkout
      - rubocop_challenge
  release:
    executor: default
    steps:
      - setup
      - release

workflows:
  version: 2

  commit:
    jobs:
      - build:
          name: build_on_ruby_2.4
          ruby_version: '2.4'
      - build:
          name: build_on_ruby_2.5
          ruby_version: '2.5'
      - build:
          name: build_on_ruby_2.6
          ruby_version: '2.6'
      - build:
          name: build_on_ruby_latest
          ruby_version: 'latest'
      - rubocop
      - yardoc
      - verify_rubocop_challenge
      - release:
          context: RubyGems API Key
          requires:
            - build_on_ruby_2.4
            - build_on_ruby_2.5
            - build_on_ruby_2.6
            - build_on_ruby_latest
            - rubocop
          filters:
            branches:
              only:
                - production

  challenge:
    triggers:
      - schedule:
          cron: "30 23 * * *" # 8:30am every day (JST)
          filters:
            branches:
              only:
                - master
    jobs:
      - rubocop_challenge
